main : main.cpp data.cpp admin.cpp
	g++ -w -std=c++17 -c data.cpp -o data.o
	g++ -w -std=c++17 -c admin.cpp -o admin.o
	g++ -w -std=c++17 -c main.cpp -o main.o
	g++ -w -std=c++17 -o main main.o data.o admin.o